In [6]:
import numpy as np

a = np.random.randn(5)

print(a)
print(a.shape) # a rank 1 array: neither a column nor a row vector!
print(a.T)

print(np.dot(a, a.T)) # maybe gives a matrix? Nope! Just a number!

a = a.reshape((5, 1)) # allows reshaping rank one array into a vector!

[-0.5988369   1.12399344  0.15402631 -0.84357438 -0.65801459]
(5,)
[-0.5988369   1.12399344  0.15402631 -0.84357438 -0.65801459]
2.79029192122508


In [13]:
a = np.random.randn(5, 1)
print(a)
print(a.shape)
print(a.T)
print(a.T.shape)

dot = np.dot(a, a.T)
print(dot)
print(dot.shape)

# Conclusion: do not use rank 1 arrays!

[[-0.75138476]
 [ 0.74723639]
 [ 0.6271882 ]
 [-1.05911506]
 [ 1.22348491]]
(5, 1)
[[-0.75138476  0.74723639  0.6271882  -1.05911506  1.22348491]]
(1, 5)
[[ 0.56457906 -0.56146204 -0.47125966  0.79580292 -0.91930792]
 [-0.56146204  0.55836223  0.46865785 -0.79140932  0.91423245]
 [-0.47125966  0.46865785  0.39336504 -0.66426447  0.7673553 ]
 [ 0.79580292 -0.79140932 -0.66426447  1.12172472 -1.29581129]
 [-0.91930792  0.91423245  0.7673553  -1.29581129  1.49691531]]
(5, 5)


In [14]:
# helps to make sure the dimension is as expected:
assert(a.shape == (5,1))
